### ISSUE TITLE
[Styling] Button icons seem to be off if using fontawesome

### ISSUE THREAD

**Issue by wucherpfennig** [kevinpapst/TablerBundle#81]
I do not know whether somebody noticed it but with the default tabler css the button icons just seem to be off if you are using fontawesome. (they always seem to have the same size)

![grafik](https://user-images.githubusercontent.com/3634653/169345478-08f09787-37e2-4837-b5ee-7bd8a2e8074f.png)

However if I add some "corrections" to the `icon` class like:

```scss
.page {
  .icon {
    font-size: 1em !important;
    height: 1.25em;
    margin: 0 .5em 0 -.5em;
    width: 1.25em;
    line-height: 1.25em;
  }
}
```

![grafik](https://user-images.githubusercontent.com/3634653/169346458-ade704fe-e78f-415b-a262-d9772f55022d.png)

It just looks better. 

I do not know what to do with this information but I wanted to share this "fix" if somebody is using multiple button sizes on their project.

BR wucherpfennig

**Comment by kevinpapst** [comment]
Yes, as the original bundle is using the SVG tabler icon set, the classes don't work perfectly.

You should use the button macro instead:
https://github.com/kevinpapst/TablerBundle/blob/main/docs/components-buttons.md

Icon mapping is done through tabler.yaml.

**Comment by wucherpfennig** [comment]
Thank you for your input. I actually tried to use your macro but using it like:

```twig
{% from '@Tabler/components/buttons.html.twig' import link_button %}

{% set urlNotification = path('notification_view', {'id': notification.id }) %}

{{ link_button('Ansicht', urlNotification, 'fa fa-eye', 'primary', 'sm' )}}

{% from '@Tabler/components/button.html.twig' import button %}

{{ button('fa fa-eye' , {title : 'Ansicht'|trans, combined: 1, buttonType: 'a', url: urlNotification, class: 'btn-sm'}, 'primary') }}
```

will always add the "faulty" `icon` class. Having a look at the button macro (not the link_button) the output from 

```twig
        {%- if icon is not same as (false) -%}
            {{ tabler_icon(icon, true, icon) }}
        {% endif %}
```

always yields in a icon class.

If you are ok with it I would later write a PR allowing overriding the `$withIconClass` via the button macro. eg. 

```twig
....
   {% set icon = values.icon ?? icon %}
>>   {% set withIconClass = values.withIconClass ?? false %}
....
    {%- if icon is not same as (false) -%}
>>            {{ tabler_icon(icon, withIconClass, icon) }}
     {% endif %}
```

**Comment by kevinpapst** [comment]
Please try the demo, it will explain the usage. We use the theme and the macro in multiple projects without problems. All of the 7 buttons for example are generated with the macros:
<img width="770" alt="Bildschirmfoto 2022-05-19 um 21 21 58" src="https://user-images.githubusercontent.com/533162/169386090-3f662641-a0e6-4b62-8463-06332ab2e54c.png">

But if you think we can improve it, please go ahead and sent a PR for the demo.
The demo contains dozens of working examples and if they look the same or even better afterwards: 👍

**Comment by wucherpfennig** [comment]
I do see what you mean. My "fix" would actually make many things worse. What I do not like about tabler + fontawesome that the icons do not scale. 

as for now I will apply the following scss to my project as it yields in a "better" scaling of the icons. 

```scss
.page {
  .btn{
    .icon {
      font-size: 125%;
      height: 1.25em;
      margin: 0 .5em 0 -.25em;
      width: 1.25em;
      line-height: 1.25em;
    }
  }
  .btn-icon{
    .icon{
      margin: 0 -1em;
    }
  }
}
```

![grafik](https://user-images.githubusercontent.com/3634653/169398314-70dd3443-2bed-463a-b986-fc4627794120.png)

It's not perfect but it is was it is ;-)

BR wucherpfennig
